### ISSUE TITLE
Register an account

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/pp-commerce-261124#1]
### **User Story**
As a [site user], I can [easily register for an account] so that I [have a personal account and be able to view my profile].

### **Acceptance Criteria**

- [ ] [User can register]
- [ ] [Describe the second criterion]
- [ ] [Describe the third criterion]

### **Tasks**

- [ ] **Task 1:** [install Allauth and add to requierements.txt ]
- [ ] **Task 2:** [adjust Settings.py, add urls path]
- [ ] **Task 3:** [migrate model base]
- [ ] **Task 4:** [update domain in Administration]
- [ ] **Task 5:** [confirm emai to be recognised by Allauth]
- [ ] **Task 6:** [test functionality]
- [ ] **Task 7:** [document testing]
