### ISSUE TITLE
All Courses View

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/pp-commerce-261124#11]
## User Story

**As a** user, **I can** see all products,  **so that** I know which one fits my needs.

### Acceptance Criteria (AC)
- [ ] Page is visible
- [ ] Content of categories is rendered 
- [ ] functionality is tested

### Tasks
- [ ] Task 1: create template
- [ ] Task 2: create view in products app and URLS
- [ ] Task 3: test functionality
