### ISSUE TITLE
Bug _ background capture should be transparent to improve UI

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/pp-commerce-261124#12]
## User Story

**As a** user **I don't want**  the background image to distract me from reading the textual context,  **so that** I can focus on reading material 

### Acceptance Criteria (AC)
- [ ] background image has opacity 0.2
- [ ] Criterion 2
- [ ] Criterion 3

### Tasks
- [ ] Task 1: refactor base.html, base.css and categories.html page
- [ ] Task 2: [description of task]
- [ ] Task 3: [description of task]
