### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/pp-commerce-261124#13]
## User Story

**As a** user, **I can** see the site's favicon in the browser's navbar,  **so that** I can recognise it between many tabs.

### Acceptance Criteria (AC)
- [ ] favicon is visible
- [ ] Criterion 2
- [ ] Criterion 3

### Tasks
- [ ] Task 1: adjust settings and static files
- [ ] Task 2: [description of task]
- [ ] Task 3: [description of task]

**Comment by VladaAlek** [comment]
Unresolved - non-critical feature
