### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/pp-commerce-261124#14]
## User Story

**As a** user, **I get** notification that the desired page is not availbele,  **so that**  I can return to courses overview page .

### Acceptance Criteria (AC)
- [x] 404 page exist
- [x] functional button to courses overview page exist
- [x] functionality is tested

### Tasks
- [x] Task 1: create template and function in disaster-ready app
- [x] Task 2: add functional button
- [x] Task 3: test functionality
