### ISSUE TITLE
Quickly recover my password

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/pp-commerce-261124#3]
### **User Story**
As a [site user], I can [quickly recover my password in case I forget it] so that I [recover access to my account].

### **Acceptance Criteria**

- [ ] [functionality is present]
- [ ] [Describe the second criterion]
- [ ] [Describe the third criterion]

### **Tasks**

- [ ] **Task 1:** [Describe the first task]
- [ ] **Task 2:** [Describe the second task]
- [ ] **Task 3:** [Describe the third task]

**Comment by VladaAlek** [comment]
Unrealized! Returned to backlog!
