### ISSUE TITLE
Stripes Card Input Form

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/pp-commerce-261124#35]
As a **user**, I can **pay for the digital services**, so I **use digital learning material**.

**Acceptance Criteria (AC)**

1. [x] Money transaction is possible - AC inappropriate/ignore

2. [x] Stripe is installed

3. [x] Stripe public key is added

4. [x] Card Input Form exists

5. [x] Basic Functionality is tested

**Tasks**

Task 1: [x] create 
Task 2: [x] install Stripe 
Task 3: [x]  add stripe public key
Task 4: [x] ad Card Input Form
Task 5: [x] Test **BASIC**functionality
