### ISSUE TITLE
Payment Intent

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/pp-commerce-261124#37]
As a **user**, I can **feel up the user's form**, so I **send data where the digital product should be delivered**.

**Acceptance Criteria (AC)**

1. [x] Form is functional (basic functionality present)

2. [x] Form is functional (advanced functionality present — saving form data)

3. [x] Functionality is present and tested

**TASKS**

Task 1: [x] create payment intention

Task 2: [x] Create cancellation and success templates, **only the last one made, the first one is not needed**, 

Task 3: [x] Add event listener in stripe_elements

Task 4: [x] add functionality to handle the POST method

Task 5: [x] Test and document the functionality (additional testing conducted)
