### ISSUE TITLE
email confirmation

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/pp-commerce-261124#4]
### **User Story**
As a [site user], I can [receive an email confirmation after registering] so that I [verify that my account registration was successful].

### **Acceptance Criteria**

- [ ] [User get an emal confirmation]
- [ ] [Describe the second criterion]
- [ ] [Describe the third criterion]

### **Tasks**

- [ ] **Task 1:** [Describe the first task]
- [ ] **Task 2:** [Describe the second task]
- [ ] **Task 3:** [Describe the third task]
