### ISSUE TITLE
Profile App

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/pp-commerce-261124#40]
As a **user**, I can **have my profile built with the possibility to adjust it**, so I **don't have to enter billing and delivery data for each shopping**.

**Acceptance Criteria (AC)**

1. [x] Profile App exists

2. [x] Template exists
4. [x] CRUD functionality is present
5. [x] initial functionality is tested and documented

**Tasks**

Task 1: [x] create Profile App

Task 2: [x] create templates with the CRUD functionality
2a) C
2b) R
2c) 'Update' functionality added
2d) D 

Task 3: [x] test and document functionality
