### ISSUE TITLE
Profile Accounts Uniform Templates

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/pp-commerce-261124#42]
As a **user**, I get **unified design of the templates related to profile activities**, so I **benefit from the improved UI**.

**Acceptance Criteria (AC)**

1. [x] All templates related to Profile Accounts offer uniformed or similar UI

2. [x] Templates are styled

3. [x] Initial functionality is tested and documented

**Tasks**

Task 1: [x] Refactor templates in the account folder 

Task 2: [x] style the templates

Task 3: [x] initial test and document functionality
