### ISSUE TITLE
personalized user profile

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/pp-commerce-261124#5]
### **User Story**
As a [site user], I can [have a personalized user profile] so that I [view my personal order history and order confirmations, and save my payment information].

### **Acceptance Criteria**

- [ ] [personalized user profile exist and it is functional]
- [ ] [Describe the second criterion]
- [ ] [Describe the third criterion]

### **Tasks**

- [ ] **Task 1:** [Describe the first task]
- [ ] **Task 2:** [Describe the second task]
- [ ] **Task 3:** [Describe the third task]
