### ISSUE TITLE
Home Page Design

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/pp-commerce-261124#6]
## User Story

**As a** user,  **I can** land upon the landing page upon visiting the site,  **so that** want to explore its content and get most important information .

### Acceptance Criteria (AC)
- [x] Landing page is designed
- [x] Mock-up is created
- [x] Home App in Django is created
- [x] Home page is functional and responsive
### Tasks
- [x] Task 1: install Home app
- [x] Task 2: design landing page
- [x] Task 3: test functionality
