### ISSUE TITLE
NAVBAR

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/pp-commerce-261124#7]
## User Story

**As a** user,  **I can** navigate the site by using navbar links,  **so that** explore the sites content easilly.

### Acceptance Criteria (AC)
- [x] Navbar is designed, and the designing process is well documented in Readme.md file
- [x] Code is delivered and the navbar is extended to all pages
- [x] functionality is tested
### Tasks
- [x] navbar is designed, and the designing process is well-documented
- [x] write DRY code
- [x] test navbar's responsivnes and functionality of the links
