### ISSUE TITLE
Seach Products Options in Navbar

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/pp-commerce-261124#8]
## User Story

**As a** [user],  **I can** [navigate to different products / or search for them],  **so that** [find them easily].

### Acceptance Criteria (AC)
- [ ] There is a categories drop-down menu
- [ ] There is a functional search bar
- [ ] 
### Tasks
- [ ] Task 1: [create mock-up]
- [ ] Task 2: [create front-end elements]
- [ ] Task 3: [create product models]
- [ ] Task 4: [create back-end elements]
- [ ] Task 5: [test functionality]

**Comment by VladaAlek** [comment]
As a noncritical feature of this project, this task is to be realised in later stages of development.
