### ISSUE TITLE
Login and Logout in Navbar

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/pp-commerce-261124#9]
## User Story

**As a** [user],  **I can** [login/logout on the main navbar],  **so that** [I know my logging status by looking at the navbar].

### Acceptance Criteria (AC)
- [x] login/logout are present in the navbar
- [x] login/logout are functional and tested
- [ ] 
### Tasks
- [x] Task 1: code front end elements
- [x] Task 2: code back and elements
- [x] Task 3: test functionality
